language: python

python:
    - "3.7.1"

script:
    - pytest

    - coverage run --source app -m py.test

    - coverage report -m

    - codeclimate-test-reporter --file .coverage

after_success:
  - coveralls
  
  - codeclimate-test-reporter