language: python

python:
    - "3.6.0"

install: 
    - "pip install -r requirements.txt"
    - "pip install pytest pytest-cov"
    - "pip install coveralls"


script: "pytest --cov=testAPI"

after_success: "coveralls"