language: python

python:
    - "3.6.0"

install: 
    - "pip install -r requirements.txt"
    - "pip install pytest"
    - "pip install pytest-cov"
    - "pip install coveralls"

script: 
    - "pytest testAPI.py"
    - "coverage run --source=incident testAPI.py test"
    - "nosetests"

after_success: "coveralls"