language: python

python:
    - "3.6.0"

install: 
    - "pip install -r requirements.txt"
    - "pip install pytest"
    - "pip install pytest-cov"
    - "pip install coveralls"

script: 
    - "pytest test_api.py"
    - "pytest --cov=."
    - "nosetests"

after_success: "coveralls"